const fs = require('fs');
const path = require('path');

const pagePath = path.join(__dirname, '../src/app/page.tsx');
let pageContent = fs.readFileSync(pagePath, 'utf8');

// Replace brand strings
pageContent = pageContent.replace(/Last-Mile Delivery Tracker/g, 'SwiftMile Logistics');
pageContent = pageContent.replace(/Last-Mile Tracker/g, 'SwiftMile Tracker');

fs.writeFileSync(pagePath, pageContent, 'utf8');
console.log('Renamed brand in page.tsx successfully!');

const layoutPath = path.join(__dirname, '../src/app/layout.tsx');
let layoutContent = fs.readFileSync(layoutPath, 'utf8');

// Replace metadata
layoutContent = layoutContent.replace(/title: "Create Next App"/g, 'title: "SwiftMile Logistics"');
layoutContent = layoutContent.replace(/description: "Generated by create next app"/g, 'description: "Logistics Operations and Delivery Management Dashboard"');

fs.writeFileSync(layoutPath, layoutContent, 'utf8');
console.log('Renamed metadata in layout.tsx successfully!');
